### ISSUE TITLE
MPI adios2

### ISSUE THREAD

**Issue by pelahi** [alxndrwllmsn/base-accessors#2]
So I wonder what the best way of generating all the functionality for parallel IO is. Currently my plan is the branch off the adios configuration branch and see if I can minimally subclass from `CasaADIOSImageAccess` but this might require more work than I expect.

**Comment by alxndrwllmsn** [comment]
Hmm, we'll need to be able to pass the communicator down to the storage manager at cube creation. There is a CubeComms class that manages this on the ContinuumMaster/Worker level, but this doesn't get passed to the CubeBuilder. Looking at CubeBuilder, it doesn't seem to use the Parallel Image Accessor Factory at all. I wonder if it's used elsewhere.

**Comment by alxndrwllmsn** [comment]
@pelahi I've created a new branch for this issue (adios_integration_mpi). I've only changed the 'create' constructor of ADIOSImage as the Table constructors in casacore only take a communicator during creation, not when accessing after creation. I was hopeful that this would somehow pass this around in the background, but I don't think it's done what I expected.

This doesn't throw an error when running but gets stuck in a deadlock at the storage manager creation. It gets stuck on a call to MPI_Comm_dup in source/adios2/helper/adiosCommMPI.cpp

**Comment by alxndrwllmsn** [comment]
@pelahi I've figured out the problem. The solution might be a bit more involved. 
The MPI_Comm_dup operation is collective, which means it's waiting for all other tasks to do it as well. In Imager, we generally have one task creating the cube, which means that only one task goes through the makeTable step. On top of that, we have a task that is used as a master task, that doesn't get involved in the operation at all. Using MPI_COMM_WORLD doesn't work because it's waiting for all of the tasks to go through the creation step.

**Comment by alxndrwllmsn** [comment]
I think, somehow, we need the communicator passed down through cubebuilder, and we need all worker tasks to go through the cube-creation step.

**Comment by alxndrwllmsn** [comment]
The CubeComms class has a method that sets all writers as CubeCreators and a method that returns the writers' communicator. We just need to pass this through CubeBuilder.

**Comment by pelahi** [comment]
Would this impact the code in such a fashion that other modes of operation would be impacted?

**Comment by alxndrwllmsn** [comment]
I'm trying to avoid it affecting other things. Most of it relies on the inclusion of a imagetype="adios" switch so that it would function as normal otherwise. Unfortunately, the imager and cubebuilder changes are directly in the yandasoft repo, of which I have a separate fork. I'll add you to that one as well.

**Comment by alxndrwllmsn** [comment]
@pelahi One more problem to add to the pile...

I've been looking through how askapsoft deals with the MPI comms. It looks like the actual communicators are private and not returned by any of the askapparallel/MPIComms/CubeComms methods. What is returned is an index to the private itsCommunicators vector that holds the communicators, not the communicator itself. 

My best idea at this point would be to get a list of writer ranks and create our own communicator that includes these. It seams like a bit of double handling, but I can't see another way, without adding another method to MPIComms/Askapparallel that returns the communicator for an index.

Let me know if I'm missing anything here.

**Comment by pelahi** [comment]
Hi @alxndrwllmsn sorry for the late comment. This is a thorny issue and I personally think a rewrite to provide communicators and pass them around is a better solution in the long term. However, that would really change the way the comms are currently accessed. 

I think we could implement a API to pass a communicator
```cpp
MPI_Comm CubeComms::GetCurrentCommunicator() { return comm;}
```
and then update the API of `MPIComms` and `AskapParallel`. Thoughts?

**Comment by alxndrwllmsn** [comment]
Sounds like what I've been looking at. I've added it in MPIComms as:
```c++
MPI_Comm MPIComms::getComm(size_t comm_index) 
{
return itsCommunicators[comm_index]
}
```
itsCommunicators is a private variable, so I don't think it's accessible up the chain (although we can change this). 
I'm busy testing it now, I still get an Invalid communicator error, so I'm trying to figure out where that is coming from.

**Comment by alxndrwllmsn** [comment]
Closing for now as the branch has been merged.
